# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/user/project/riscv2/constraints/constraints.xdc

# Block Designs: /home/user/project/riscv2/bd/riscvTop/riscvTop.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop || ORIG_REF_NAME==riscvTop} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_ramTop_0_0/riscvTop_ramTop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_ramTop_0_0 || ORIG_REF_NAME==riscvTop_ramTop_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_PC_0_0/riscvTop_PC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_PC_0_0 || ORIG_REF_NAME==riscvTop_PC_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_ModeFSM_0_0/riscvTop_ModeFSM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_ModeFSM_0_0 || ORIG_REF_NAME==riscvTop_ModeFSM_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_FetchLatch_0_0/riscvTop_FetchLatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_FetchLatch_0_0 || ORIG_REF_NAME==riscvTop_FetchLatch_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_Decode_0_0/riscvTop_Decode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_Decode_0_0 || ORIG_REF_NAME==riscvTop_Decode_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_ExecStage_0_0/riscvTop_ExecStage_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_ExecStage_0_0 || ORIG_REF_NAME==riscvTop_ExecStage_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_RegFile_0_0/riscvTop_RegFile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_RegFile_0_0 || ORIG_REF_NAME==riscvTop_RegFile_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_RegFileWriteArbiter_0_0/riscvTop_RegFileWriteArbiter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_RegFileWriteArbiter_0_0 || ORIG_REF_NAME==riscvTop_RegFileWriteArbiter_0_0} -quiet] -quiet

# IP: /home/user/project/riscv2/bd/riscvTop/ip/riscvTop_orGate_0_0/riscvTop_orGate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscvTop_orGate_0_0 || ORIG_REF_NAME==riscvTop_orGate_0_0} -quiet] -quiet

# XDC: /home/user/project/riscv2/bd/riscvTop/riscvTop_ooc.xdc
