# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/user/project/riscv2/constraints/constraints.xdc

# Block Designs: bd/simpleRisc/simpleRisc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc || ORIG_REF_NAME==simpleRisc} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_aluMuxComb_0_0/simpleRisc_aluMuxComb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_aluMuxComb_0_0 || ORIG_REF_NAME==simpleRisc_aluMuxComb_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_Decode_0_0/simpleRisc_Decode_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_Decode_0_0 || ORIG_REF_NAME==simpleRisc_Decode_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_RegFile_0_0/simpleRisc_RegFile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_RegFile_0_0 || ORIG_REF_NAME==simpleRisc_RegFile_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_writeBackLatch_0_0/simpleRisc_writeBackLatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_writeBackLatch_0_0 || ORIG_REF_NAME==simpleRisc_writeBackLatch_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_bypassMux_0_0/simpleRisc_bypassMux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_bypassMux_0_0 || ORIG_REF_NAME==simpleRisc_bypassMux_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_opLatch_0_0/simpleRisc_opLatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_opLatch_0_0 || ORIG_REF_NAME==simpleRisc_opLatch_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_alu_0_0/simpleRisc_alu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_alu_0_0 || ORIG_REF_NAME==simpleRisc_alu_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_pcAlu_0_0/simpleRisc_pcAlu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_pcAlu_0_0 || ORIG_REF_NAME==simpleRisc_pcAlu_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_pcMuxSelector_0_0/simpleRisc_pcMuxSelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_pcMuxSelector_0_0 || ORIG_REF_NAME==simpleRisc_pcMuxSelector_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_execLatch_0_0/simpleRisc_execLatch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_execLatch_0_0 || ORIG_REF_NAME==simpleRisc_execLatch_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_resetManager_0_0/simpleRisc_resetManager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_resetManager_0_0 || ORIG_REF_NAME==simpleRisc_resetManager_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_fakeMemIO_0_0/simpleRisc_fakeMemIO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_fakeMemIO_0_0 || ORIG_REF_NAME==simpleRisc_fakeMemIO_0_0} -quiet] -quiet

# IP: bd/simpleRisc/ip/simpleRisc_PC_0_0/simpleRisc_PC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simpleRisc_PC_0_0 || ORIG_REF_NAME==simpleRisc_PC_0_0} -quiet] -quiet

# XDC: /home/user/project/riscv2/genProject/riscv2/riscv2.gen/sources_1/bd/simpleRisc/simpleRisc_ooc.xdc
