# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/DualBRAM/DualBRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DualBRAM || ORIG_REF_NAME==DualBRAM} -quiet] -quiet

# XDC: /home/user/project/riscv2/riscv2.gen/sources_1/ip/DualBRAM/DualBRAM_ooc.xdc
