# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32.xci
# IP: The module: 'dualPortRAM32kx32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualPortRAM32kx32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32.xci
# IP: The module: 'dualPortRAM32kx32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualPortRAM32kx32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
