# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/project/riscv2/genProject/riscv2/riscv2.srcs/sources_1/bd/simpleRisc/ip/simpleRisc_ROMRAM_0_0/simpleRisc_ROMRAM_0_0.xci
# IP: The module: 'simpleRisc_ROMRAM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualPortRAM32kx32 || ORIG_REF_NAME==dualPortRAM32kx32} -quiet] -quiet

# XDC: /home/user/project/riscv2/genProject/riscv2/riscv2.gen/sources_1/bd/simpleRisc/ip/simpleRisc_ROMRAM_0_0/simpleRisc_ROMRAM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simpleRisc_ROMRAM_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/project/riscv2/genProject/riscv2/riscv2.srcs/sources_1/bd/simpleRisc/ip/simpleRisc_ROMRAM_0_0/simpleRisc_ROMRAM_0_0.xci
# IP: The module: 'simpleRisc_ROMRAM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/user/project/riscv2/ips/dualPortRAM32kx32/dualPortRAM32kx32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualPortRAM32kx32 || ORIG_REF_NAME==dualPortRAM32kx32} -quiet] -quiet

# XDC: /home/user/project/riscv2/genProject/riscv2/riscv2.gen/sources_1/bd/simpleRisc/ip/simpleRisc_ROMRAM_0_0/simpleRisc_ROMRAM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simpleRisc_ROMRAM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
